export const HANDLE_FIRST_NAME_CHANGE = 'HANDLE_FIRST_NAME_CHANGE';
export const HANDLE_LAST_NAME_CHANGE = 'HANDLE_LAST_NAME_CHANGE';
export const HANDLE_ANNUAL_SALARY_CHANGE = 'HANDLE_ANNUAL_SALARY_CHANGE';
export const HANDLE_SUPER_RATE_CHANGE = 'HANDLE_SUPER_RATE_CHANGE';
